### ISSUE TITLE
Switch tarantool builds to a new RPM spec

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/build#10]
Please fix #6 and #9 and then switch https://github.com/tarantool/tarantool/ builds to the new spec (replace tarantool.spec with fedora.spec). `extra/rpm` folder is also legacy. Please discuss with @bigbes and then before remove this dir too.

See https://github.com/tarantool/tarantool/commit/41cf2ee968ae1ac4da4ac310c5bf2d8434c93b8e for more details.

Blocked by: #6
Blocked by: #9

**Comment by Sulverus** [comment]
+gh-9

**Comment by rtsisyk** [comment]
Fixed.
