### ISSUE TITLE
Remove Fedora 22, add Fedora 24

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/build#16]
As of the 19th of July 2016, Fedora 22 has reached its end of life for
updates and support. No further updates, including security updates,
will be available for Fedora 22.  Please remove Fedora 22 from all repositories and add Fedora 24.

**Comment by rtsisyk** [comment]
I updated tarantool/tarantool: https://travis-ci.org/tarantool/tarantool/builds/149299146
- [ ] Update .travis.yml for all other repositories from https://travis-ci.org/tarantool/
- [ ] Drop Fedora 22 packages from packagecloud to save space

**Comment by lenkis** [comment]
I updated Fedora version info on the Download page.

**Comment by racktear** [comment]
Let's leave Fedora 22 packages on PackageCloud
