### ISSUE TITLE
builder not picking up VERSION when spinning up docker

### ISSUE THREAD

**Issue by gdevenyi** [tarantool/build#17]
Attempting to use Travis-CI to build packages, so attempting to follow the howto on README word-for word.

It appears on these lines:
https://github.com/tarantool/build/blob/master/build#L149-L150

That VERSION and RELEASE aren't getting read and propogated into the docker, which causes the build scripts to fail.

My source repo is at https://github.com/gdevenyi/minc-toolkit-v2
And the travis outputs are at:
https://travis-ci.org/gdevenyi/minc-toolkit-v2

**Comment by gdevenyi** [comment]
Looking at the code, and the logs a bit more, it looks like VERSION is not getting picked up earlier, possibly at https://github.com/tarantool/build/blob/master/build#L32

**Comment by gdevenyi** [comment]
Indeed after a quick test, that sed magics completely removes the hash of the HEAD commit, leaving the version empty.

**Comment by rtsisyk** [comment]
@gdevenyi VERSION file is created by build/pack/travis.sh script using `git describe --long --always > VERSION`. "sed magic" splits `git  describe` result to VERSION and RELEASE:

```
$ cat VERSION 
1.7.1-69-g0eefd08
$ cat VERSION | sed -n 's/^\([0-9\.]*\)-\([0-9]*\)-\([a-z0-9]*\)/\1/p'
1.7.1
$ cat VERSION | sed -n 's/^\([0-9\.]*\)-\([0-9]*\)-\([a-z0-9]*\)/\2/p'
69
```

`git describe` creates version string based on the last annotated tag (git tag -a). Unfortunally, sed expression was designed only for number.number[.number] naming scheme. I can see that you use [different scheme](https://github.com/gdevenyi/minc-toolkit-v2/releases) -  "release-1.9.10". 

It is possible to override build/build variables by creating `.build.mk` file in the root directory of your project. Please see https://github.com/tarantool/build/blob/master/build#L70 For example, we use the following [overrides](https://github.com/tarantool/build/blob/master/product.d/tarantool.mk example.) for tarantool/tarantool project:

```
# Add git hash in Debian to follow convention used by official packages
DEB_VERSION:=$(shell cat VERSION | sed -n 's/^\([0-9\.]*\)-\([0-9]*\)-\([a-z0-9]*\)/\1.\2.\3/p')
VERSION:=$(shell cat VERSION | sed -n 's/^\([0-9\.]*\)-\([0-9]*\)-\([a-z0-9]*\)/\1.\2/p')
RELEASE:=1
```

Tarantool 1.7.1-69-g0eefd08 has tarantool_1.7.1.69.g0eefd08-1_amd64.deb (VERSION=1.7.1.69.g0eefd08, RELEASE=1)  and tarantool-1.6.8.744-1.fc23.x86_64.rpm (VERSION=1.6.8.744 RELEASE=1) packages according to rules above. Default is VERSION=1.7.1, RELEASE=69.

You can set custom values for VERSION/RELEASE (or DEB_VERSION/DEB_RELEASE/RPM_VERSION/RPM_RELEASE) in you .build.mk to support "release-x.y.z" scheme.

Thanks for your interest to this project!
Please show your Travis CI logs, I'll try to help you.

**Comment by gdevenyi** [comment]
Thanks for the feedback, logs are at https://travis-ci.org/gdevenyi/minc-toolkit-v2

Thanks for the info on the overrides, I'll try those out later (after you have a change to look over the logs)

**Comment by gdevenyi** [comment]
It seems ``git describe --long --always`` only returns a tiny hash
```
> git describe --long --always
acf40b5
```

However, I found an alternate:
```
> git describe --long --always --tags
release-1.9.11-8-gacf40b5
```

In general, I was interested in building the HEAD of master, develop, and all the tagged releases. Right now, I can't tell if this tool can do this without a fork and adjustment of the code.

**Comment by rtsisyk** [comment]
`git describe --long --always --tags` also works for me.

>  Right now, I can't tell if this tool can do this without a fork and adjustment of the code.
Please feel free to send pull requests.
