### ISSUE TITLE
Make pattern matching for debian/ubuntu fails

### ISSUE THREAD

**Issue by gdevenyi** [tarantool/build#23]
For all my debian/ubuntu builds right now I get this:
https://travis-ci.org/gdevenyi/minc-toolkit-v2/jobs/147497510#L581-L583
```
Tarantool/Build for minc-toolkit-v2 1.9.10
make: *** No rule to make target `ubuntu-precise'.  Stop.
Build failed
```

Similarly for all other debian and ubuntu jobs.

https://github.com/tarantool/build/blob/master/build#L215-L218

**Comment by rtsisyk** [comment]
Hi, you have wrong structure for debian/:
```
$ minc-toolkit-v2/debian$ ls -1
debian.changelog
debian.control
debian.rules
````

Rename debian/debian.changelog to debian/changelog, debian/debian.control to debian/control
debian/debian.rules to debian/rules.

**Comment by gdevenyi** [comment]
Cheers that fixed it up. Thanks!
