### ISSUE TITLE
Bash scripts should use "unofficial strict mode"

### ISSUE THREAD

**Issue by gdevenyi** [tarantool/build#25]
The makefile side of building fails out with error codes properly, however other commands within travis.sh don't.

For example, my packagecloud was full, the travis.sh continued to run "successfully" because bash will happily continue on with an error.

Scripts should error out immediately on error.

http://redsymbol.net/articles/unofficial-bash-strict-mode/

I'm going to try this out later, sometimes it can expose latent errors in scripts so it should be tested before implementing.

**Comment by rtsisyk** [comment]
Fixed in packpack
