### ISSUE TITLE
Doesn't work with some semantic version strings

### ISSUE THREAD

**Issue by SteveGilvarry** [tarantool/build#28]
FYI I am playing with a project that uses semantic versioning and does pre-releases, so I get v1.30.0-rc1-0-xxxxx or v1.30.0-14-geef95da. https://github.com/ZoneMinder/ZoneMinder/releases
The first issue is the v in the tags causes Version to return empty after build does its sed. I can probably handle that one easily, but not sure how to pull rc1 part of the string also when it is needed as it is also separated by -.

If I found a way around it that works with ours and your versioning I will PR it back, but if anyone has any ideas I am happy to hear about them.

**Comment by racktear** [comment]
Hi @SteveGilvarry . Thanks for reaching out.
You are correct. Strictly speaking, current version numbering is not semver. The following will be closer:
1.30.0-rc1+geef95da

Before sending the PR, could you please elaborate on your proposal? Which exact format would you like to see?

**Comment by SteveGilvarry** [comment]
@racktear We probably need to drop the v on our version number, so that is less of an issue.
Your example is correct, but not what git describe, which creates VERSION, would return which would be like this 1.30.0-rc1-14-geef95da. Currently the sed in build would fail when it gets anything non-numeric after first dash.
1.30.0-14-geef95da works
1.30.0-rc1-14-geef95da fails
Just a quick test gave me the below that would return 1.30.0 always for VERSION and 14 or rc1 respectively for RELEASE, so not a complete solution as rc1 loses the 14.
VERSION=$(shell cat VERSION | sed -n 's/^\([0-9\.]*\)-\([a-z0-9]*\)-\([a-z0-9\-]*\)/\1/p')
RELEASE=$(shell cat VERSION | sed -n 's/^\([0-9\.]*\)-\([a-z0-9]*\)-\([a-z0-9\-]*\)/\2/p')

No solution yet so nothing to propose. Was just saying if I find a solution I would share it.

**Comment by rtsisyk** [comment]
Hi, this ticket has been moved to https://github.com/packpack/packpack/issues/50
