### ISSUE TITLE
--exclude-vcs doesn't work on OS X

### ISSUE THREAD

**Issue by racktear** [tarantool/build#39]

**Comment by zmre** [comment]
A fix for this would be great.  As a temporary workaround, here's what I've been doing:

1. `brew install gnu-tar`
2. `PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"`

That should get you past the issue.  A better fix would be to just explicitly exclude the files that `--exclude-vcs` excludes, which the [man page](https://www.gnu.org/software/tar/manual/html_section/tar_49.html) shows as:

```
As of version 1.29, the following files are excluded:

'CVS/', and everything under it
'RCS/', and everything under it
'SCCS/', and everything under it
'.git/', and everything under it
'.gitignore'
'.gitmodules'
'.gitattributes'
'.cvsignore'
'.svn/', and everything under it
'.arch-ids/', and everything under it
'{arch}/', and everything under it
'=RELEASE-ID'
'=meta-update'
'=update'
'.bzr'
'.bzrignore'
'.bzrtags'
'.hg'
'.hgignore'
'.hgrags'
'_darcs'
```

I'd submit a PR, but so far my other PRs have been ignored and so I'm reluctant to put more effort into the project.

**Comment by rtsisyk** [comment]
@zmre All your pull requests have been merged. Sorry for the delay and thanks for your the contribution.

>  A better fix would be to just explicitly exclude the files that --exclude-vcs excludes, which the man page shows as:

OK.
What is about  `--exclude-vcs-ignores` on Mac?

**Comment by zmre** [comment]
Thanks for merges.  GNU tar has two relevant flags: `--exclude-vcs` which excludes `CVS` and `.git` directories and such. The other is `--exclude-vcs-ignores`, which the build doesn't use at present, but which would exclude all the files in `.gitignore` or similar.  The Mac version of `tar` doesn't have either of those flags.  Unfortunately, it doesn't seem to have an option to even read an exclude list from a file, which would be the handiest fix.  You could look for gnu-tar in the common homebrew location and just call that directly if it exists and warn the user if it doesn't. Or you could put the main exclude patterns into the command so it runs either way.  One other option would be to tar the source directory inside a docker machine.  None of those are especially pretty though.
