### ISSUE TITLE
Source tarballs

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/build#5]
The new build system should generate source tarballs at least for https://github.com/tarantool/tarantool. Source tarballs are mandatory for packaging. You will break some distros by removing source tarballs from our web site. For example, https://svnweb.freebsd.org/ports/head/databases/tarantool/Makefile?revision=400686&view=markup#l7

**Comment by Sulverus** [comment]
Tarball generation integrated with packagecloud mirror: http://tarantool.org/dist/1.6/ and with download.tarantool.org, for example: http://download.tarantool.org/tarantool/1.6/src/tarantool-1.6.8.525.tar.gz

**Comment by rtsisyk** [comment]
Implemented. Thanks @bigbes
