### ISSUE TITLE
Remove git describe --long from RPM specs

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/build#6]
This is a rubbish:
```
Source1: VERSION
%global build_version %(( cat %{SOURCE1} || git describe --long) | sed "s/[0-9]*\.[0-9]*\.[0-9]*-//" | sed "s/-[a-z 0-9]*//")
%global git_hash %((cat %{SOURCE1} || git describe --long) | sed "s/.*-//")
%global prod_version %((cat %{SOURCE1} || git describe --long) | sed "s/-[0-9]*-.*//")
```

Please use rpmdev-bumpspec to update version and changelog:
```
rpmdev-bumpspec orig.spec -n $(VERSION) -c "automated build"  --user "Tarantool Buildbot <build@tarantool.org>"
```
`-n` is only supported on the latest Fedora, but you can include this script to your repository.

The original spec must have some version set by default to work without your build scripts (e.g 1.6.8.0 for Tarantool). The main problem here is that some packages require the commit number (e.g. tarantool-1.6.8.287-1) whether other doesn't need it (e.g. msgpuck-1.0.1-1). I think you can parse default version from the original spec, calculate the number of parts and then take the appropriate number of parts from the output of `git describe --long --always`. 

Please note that `Release:` tag must not be used for the commit number. This fields indicates revision of spec file itself. Distro maintainers may increment this field for some internal purposes, e.g during automatic rebuilds. The only correct value for us here is `Release: 1%{?dist}`.

Test you code with new Fedora spec files I've made for for tarantool and msgpuck.

**Comment by Sulverus** [comment]
Done. Implemented sed based rpm bump for spec

**Comment by rtsisyk** [comment]
Great!
