### ISSUE TITLE
Upload packages to tarantool.org

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/build#7]
The new build system must upload all packages to our repository on tarantool.org
It doesn't matter how do you plan archive that. You can continue to use packagecloud as a temporary storage, but I personally don't see any reasons to have one extra service just to upload already created rpm/deb files to our web-site.

Don't forget that all packages on tarantool.org must be signed by our release keys. This is a mandatory requirement.

**Comment by Sulverus** [comment]
1. Mirror enabled for http://tarantool.org/dist/1.6/
2. Generated new gpg: "Tarantool packages archive key"

After discussion with @rtsisyk we decide to merge our release key with packagecloud's, so gpg key is available in  [web](http://download.tarantool.org/tarantool/1.6/gpgkey) and can be used with any 1.6 repository(archive or packagecloud)
