### ISSUE TITLE
Remove devtoolset from RPM specs

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/build#9]
Please remove devtoolset, Lua and other garbage from RPM specs.
You can prepare a proper Docker image to allow `rpmbuild -b`  to work out of the box.
Please take my Dockerfile for CentOS 6 as an example:
https://github.com/rtsisyk/docker/blob/cd45ae7d82452a9e151c201d26f584e61080d4c3/centos6/Dockerfile#L12

**Comment by Sulverus** [comment]
devtoolset variables export moved to docker file
